namespace Yotei.Tools.Generators.Internal;

// ========================================================
/// <summary>
/// Represents a file-alike top-most node in the source code generation hierarchy.
/// </summary>
internal sealed class FileNode : INode
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="fileName"></param>
    public FileNode(string fileName) => FileName = fileName.NotNullNotEmpty();

    /// <inheritdoc/>
    public override string ToString() => $"File: {FileName}";

    /// <summary>
    /// The name of this file, without extensions.
    /// </summary>
    public string FileName { get; }

    // -----------------------------------------------------

    /// <summary>
    /// The collection of child namespaces registered into this node.
    /// </summary>
    public ChildNamespaces ChildNamespaces { get; } = [];

    // -----------------------------------------------------

    /// <summary>
    /// Invoked before generation to validate this node, and its child ones, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public bool Validate(SourceProductionContext context)
    {
        foreach (var node in ChildNamespaces) if (!node.Validate(context)) return false;
        return true;
    }

    // -----------------------------------------------------

    /// <summary>
    /// Invoked to emit the source code for this node, and its child ones, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    public void Emit(SourceProductionContext context, CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();

        EmitPragmas(cb);
        EmitUsings(cb);

        var done = false;
        foreach (var node in ChildNamespaces)
        {
            if (done) cb.AppendLine(); done = true;
            node.Emit(context, cb);
        }
    }

    /// <summary>
    /// Generates file-level pragmas.
    /// </summary>
    void EmitPragmas(CodeBuilder cb)
    {
        var items = new List<string>();

        foreach (var node in ChildNamespaces)
        {
            var tree = node.Syntax.SyntaxTree;
            if (tree.TryGetText(out var text))
            {
                foreach (var line in text.Lines)
                {
                    var str = line.ToString().Trim();
                    if (str.StartsWith("#pragma") && !items.Contains(str)) items.Add(str);
                    else if (str.StartsWith("namespace")) break;
                }
            }
        }

        if (items.Count > 0)
        {
            foreach (var item in items) cb.AppendLine(item);
            cb.AppendLine();
        }
    }

    /// <summary>
    /// Generates file-level usings.
    /// </summary>
    void EmitUsings(CodeBuilder cb)
    {
        var items = new List<string>();

        foreach (var node in ChildNamespaces)
        {
            var comp = node.Syntax.GetCompilationUnitSyntax();
            foreach (var item in comp.Usings)
            {
                var str = item.ToString().Trim();
                if (!string.IsNullOrWhiteSpace(str) && !items.Contains(str)) items.Add(str);
            }
        }

        if (items.Count > 0)
        {
            foreach (var item in items) cb.AppendLine(item);
            cb.AppendLine();
        }
    }
}