--- =============================================
PRINT 'CREATING THE TEST DATABASE...'
--- =============================================

USE [Master];

CREATE DATABASE [YoteiDB];

ALTER DATABASE [YoteiDB] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [YoteiDB] SET ANSI_NULLS OFF;
ALTER DATABASE [YoteiDB] SET ANSI_PADDING OFF;
ALTER DATABASE [YoteiDB] SET ANSI_WARNINGS OFF;
ALTER DATABASE [YoteiDB] SET ARITHABORT OFF;
ALTER DATABASE [YoteiDB] SET AUTO_CLOSE OFF;
ALTER DATABASE [YoteiDB] SET AUTO_CREATE_STATISTICS ON;
ALTER DATABASE [YoteiDB] SET AUTO_SHRINK OFF;
ALTER DATABASE [YoteiDB] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [YoteiDB] SET CURSOR_CLOSE_ON_COMMIT OFF;
ALTER DATABASE [YoteiDB] SET CURSOR_DEFAULT GLOBAL;
ALTER DATABASE [YoteiDB] SET CONCAT_NULL_YIELDS_NULL OFF;
ALTER DATABASE [YoteiDB] SET NUMERIC_ROUNDABORT OFF;
ALTER DATABASE [YoteiDB] SET QUOTED_IDENTIFIER OFF;
ALTER DATABASE [YoteiDB] SET RECURSIVE_TRIGGERS OFF;
ALTER DATABASE [YoteiDB] SET DISABLE_BROKER;
ALTER DATABASE [YoteiDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
ALTER DATABASE [YoteiDB] SET DATE_CORRELATION_OPTIMIZATION OFF;
ALTER DATABASE [YoteiDB] SET TRUSTWORTHY OFF;
ALTER DATABASE [YoteiDB] SET ALLOW_SNAPSHOT_ISOLATION OFF;
ALTER DATABASE [YoteiDB] SET PARAMETERIZATION SIMPLE;
ALTER DATABASE [YoteiDB] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [YoteiDB] SET RECOVERY FULL;
ALTER DATABASE [YoteiDB] SET MULTI_USER;
ALTER DATABASE [YoteiDB] SET PAGE_VERIFY CHECKSUM;
ALTER DATABASE [YoteiDB] SET DB_CHAINING OFF;
ALTER DATABASE [YoteiDB] SET READ_WRITE;

--- =============================================
PRINT 'TEST DATABASE CREATED...'
--- =============================================