namespace Yotei.Tools.Generators.Internal;

// ========================================================
internal static class GeneratedCodeAttr
{
    public static string ShortName { get; } = "GeneratedCode";
    public static string LongName { get; } = ShortName + "Attribute";
    public static string Tool { get; } = nameof(Tool);
    public static string Version { get; } = nameof(Version);

    // ----------------------------------------------------

    public static string Code(string nsName) => $$"""
        namespace {{nsName}}
        {
            /// <summary>
            /// Identifies code generated by a tool.
            /// </summary>
            [AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
            internal class {{LongName}} : Attribute
            {
                /// <summary>
                /// Initializes a new instance with the given tool name and version.
                /// </summary>
                /// <param name="tool"></param>
                /// <param name="version"></param>
                public {{LongName}}(string tool, string version = null)
                {
                    Tool = tool == null ? "" : version;
                    Version = version == null ? "" : version;
                }
        
                /// <summary>
                /// The name of the tool that generated the code.
                /// </summary>
                public string {{Tool}} { get; set; }
        
                /// <summary>
                /// The version of the tool that generated the code.
                /// </summary>
                public string {{Version}} { get; set; }
            }
        }
        """;

    // ----------------------------------------------------
    /// <summary>
    /// Gets the decoration for the given tool and optional version.
    /// </summary>
    /// <param name="nsName"></param>
    /// <param name="tool"></param>
    /// <param name="version"></param>
    /// <returns></returns>
    public static string GetDecorator(string nsName, string tool, string? version = null)
    {
        tool = tool.NotNullNotEmpty();
        version = version.NullWhenEmpty() ?? "";

        return $"[{nsName}.{ShortName}(\"{tool}\", \"{version}\")]";
    }

    // ----------------------------------------------------

    /// <summary>
    /// Determines if the symbol has been code generated by a tool.
    /// </summary>
    /// <param name="symbol"></param>
    /// <returns></returns>
    public static bool IsGeneratedCode(ISymbol symbol)
    {
        return symbol.HasAttributes(LongName);
    }

    /// <summary>
    /// Determines if the symbol has been code generated by a tool.
    /// </summary>
    /// <param name="symbol"></param>
    /// <param name="tool"></param>
    /// <param name="version"></param>
    /// <returns></returns>
    public static bool IsGeneratedCode(ISymbol symbol, out string tool, out string version)
    {
        tool = "";
        version = "";

        var ats = symbol.GetAttributes(LongName);
        foreach (var at in ats)
        {
            var item = at.ConstructorArguments[0];
            if (!item.IsNull && item.Value is string stool) tool = stool;

            item = at.ConstructorArguments[1];
            if (!item.IsNull && item.Value is string sversion) version = sversion;

            return true;
        }

        return false;
    }
}