namespace Yotei.Tools.Generators.Internal;

// ========================================================
internal static class YoteiGeneratedAttr
{
    public static string ShortName { get; } = "YoteiGenerated";
    public static string LongName { get; } = ShortName + "Attribute";

    // ----------------------------------------------------

    public static string Code(string nsName) => $$"""
        namespace {{nsName}}
        {
            /// <summary>
            /// Identifies code generated by the Yotei framework.
            /// </summary>
            [AttributeUsage(
                AttributeTargets.All,
                Inherited = false, AllowMultiple = false
            )]
            internal sealed class {{LongName}} : Attribute { }
        }
        """;
}