namespace Yotei.Tools.Generators.Internal;

// ========================================================
/// <summary>
/// Represents a file-alike node in the source code generation hierarchy.
/// </summary>
internal class FileNode : CodeBuilder, INode
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="hierarchy"></param>
    /// <param name="fileName"></param>
    public FileNode(Hierarchy hierarchy, string fileName)
    {
        Hierarchy = hierarchy.ThrowWhenNull();
        FileName = fileName.NotNullNotEmpty();
        NamespaceChildren = new(this);
    }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns></returns>
    public override string ToString() => $"File: {FileName}";

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public Hierarchy Hierarchy { get; }

    INode? INode.ParentNode => Hierarchy;

    /// <summary>
    /// The file name of this instance, without extensions.
    /// </summary>
    public string FileName { get; }

    /// <summary>
    /// The collection of namespace nodes registered into this instance.
    /// </summary>
    public NamespaceChildrenList NamespaceChildren { get; }
    public class NamespaceChildrenList : ChildrenList<NamespaceNode>
    {
        public NamespaceChildrenList(FileNode master) : base(master)
        {
            ItemToDebug = (item) => item.Name;
            Comparer = (x, y) => x.Name == y.Name;
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public bool Validate(SourceProductionContext context)
    {
        foreach (var node in NamespaceChildren) if (!node.Validate(context)) return false;
        return true;
    }

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    public void Print(SourceProductionContext context, CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();
        
        PrintPragmas(cb);
        Printusings(cb);

        foreach (var node in NamespaceChildren) node.Print(context, cb);
    }

    /// <summary>
    /// Emits the file-level pragmas.
    /// </summary>
    /// <param name="cb"></param>
    void PrintPragmas(CodeBuilder cb)
    {
        var items = new CustomList<string>()
        {
            Comparer = (x, y) => x == y,
            CanInclude = (@this, item) => @this.IndexOf(item) < 0,
        };

        foreach (var node in NamespaceChildren)
        {
            if (node.Syntax is null) continue;

            var tree = node.Syntax.SyntaxTree;
            if (tree.TryGetText(out var text))
            {
                foreach (var line in text.Lines)
                {
                    var str = line.ToString().Trim();
                    if (str.StartsWith("#pragma")) items.Add(str);
                    if (str.StartsWith("namespace")) break;
                }
            }
        }

        if (items.Count > 0)
        {
            foreach (var item in items) cb.AppendLine(item);
            cb.AppendLine();
        }
    }

    /// <summary>
    /// Emits the file-level usings.
    /// </summary>
    /// <param name="cb"></param>
    void Printusings(CodeBuilder cb)
    {
        var items = new CustomList<string>()
        {
            Comparer = (x, y) => x == y,
            CanInclude = (@this, item) => @this.IndexOf(item) < 0,
        };

        foreach (var node in NamespaceChildren)
        {
            if (node.Syntax is null) continue;

            var comp = node.Syntax.GetCompilationUnitSyntax();
            foreach (var item in comp.Usings)
            {
                var str = item.ToString();
                if (str != null && str.Length > 0) items.Add(str);
            }
        }

        if (items.Count > 0)
        {
            foreach (var item in items) cb.AppendLine(item);
            cb.AppendLine();
        }
    }
}