namespace Yotei.Tools.Generators;

// ========================================================
partial class TypeNode
{
    /// <summary>
    /// <inheritdoc/>
    /// <br/> This method is INFRASTRUCTURE, not intended for inheritors usage. Behavior can be
    /// customized using the <see cref="OnValidate(SourceProductionContext)"/>,
    /// <see cref="OnEmitCore(in TreeContext, CodeBuilder)"/>,  <see cref="IsSupportedKind()"/>,
    /// <see cref="GetBaseList()"/> and <see cref="OnEmitChilds(in TreeContext, CodeBuilder)"/>
    /// methods.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    /// <returns></returns>
    public bool Emit(in TreeContext context, CodeBuilder cb)
    {
        context.Context.CancellationToken.ThrowIfCancellationRequested();

        // Validation...
        if (!OnValidate(context.Context)) return false;

        // Parent elements, returning how many levels were opened...
        var num = OnEmitParents(cb);

        // This type...
        var head = GetTypeHeader(Symbol);
        var str = GetBaseList();
        if ((str = str.NullWhenEmpty(trim: true)) != null) head += $" : {str}";

        cb.AppendLine(head);
        cb.AppendLine("{");
        cb.IndentLevel++;

        var old = cb.Length;
        var ret = OnEmitCore(in context, cb);
        if (ret)
        {
            var len = cb.Length;
            if (len != old) cb.AppendLine();

            if (!OnEmitChilds(in context, cb)) ret = false;
        }
        cb.IndentLevel--;
        cb.AppendLine("}");

        // Closing he parent levels...
        for (var i = 0; i < num; i++)
        {
            cb.IndentLevel--;
            cb.AppendLine("}");
        }

        // Returning...
        return ret;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Obtains the not-normalized file name for the top-most type element carried by this
    /// instance.
    /// </summary>
    internal string EasyFileName
    {
        get
        {
            var options = new EasyTypeOptions
            {
                NamespaceStyle = EasyNamespaceStyle.Default,
                UseHost = true,
                UseSpecialNames = true,
                RemoveAttributeSuffix = false,
            };
            options.GenericListOptions = options;

            return Symbol.EasyName(options);
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// Obtains the appropriate type header.
    /// </summary>
    static string GetTypeHeader(INamedTypeSymbol symbol)
    {
        var rec = symbol.IsRecord ? "record " : string.Empty;
        var kind = symbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => throw new ArgumentException("Type kind not supported.").WithData(symbol)
        };

        // We assume the type "is in range", so a simplified name is enough...
        var options = new EasyTypeOptions
        {
            UseSpecialNames = true,
            NullableStyle = EasyNullableStyle.None,
            GenericListOptions = EasyTypeOptions.Default.WithRecursive(
                namespaceStyle: EasyNamespaceStyle.Default,
                useHost: true,
                useSpecialNames: true,
                nullableStyle: EasyNullableStyle.None)
        };

        var name = symbol.EasyName(options);        
        return $"partial {rec}{kind} {name}"; // Always a partial one...
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the host parents of this instance. Returns the number of opened levels
    /// that must be closed afterwards.
    /// </summary>
    int OnEmitParents(CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();

        return SyntaxNodes.Count == 0
            ? EmitParentsFromSymbol(Symbol, cb)
            : EmitParentsFromSyntaxNodes(Symbol, SyntaxNodes, cb);
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit parents when only the symbol is available. This method is considered as a
    /// less-rich or basic fall-back.
    /// </summary>
    static int EmitParentsFromSymbol(INamedTypeSymbol symbol, CodeBuilder cb)
    {
        // We may still be able to use syntaxes...
        var references = symbol.DeclaringSyntaxReferences;
        if (references.Length > 0)
        {
            var nodes = references.Select(x => x.GetSyntax()).OfType<BaseTypeDeclarationSyntax>();
            if (nodes.Any()) return EmitParentsFromSyntaxNodes(symbol, nodes, cb);
        }

        // The fall-back basic way...
        var nschain = symbol.GetChain().Where(static x => x is INamespaceSymbol);
        var name = string.Join(".", nschain.Select(x => x.Name));

        cb.AppendLine($"namespace {name}");
        cb.AppendLine("{");
        cb.IndentLevel++;

        var num = EmitContainingTypes(symbol, cb);
        return num + 1;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit parents when there is at least one syntax captured for the type. This
    /// method provides a richer way of doing things. Note that we still need the symbol because
    /// it is used at the end to emit the containing elements.
    /// </summary>
    static int EmitParentsFromSyntaxNodes(
        INamedTypeSymbol symbol,
        IEnumerable<BaseTypeDeclarationSyntax> syntaxes, CodeBuilder cb)
    {
        List<string> pragmas = [];
        List<string> usings = [];

        // File-level pragmas and usings...
        foreach (var syntax in syntaxes)
        {
            var nschain = syntax.GetChain().Where(static x => x is BaseNamespaceDeclarationSyntax);
            PopulateFileLevelPragmas(pragmas, nschain);
            PopulateFileLevelUsings(usings, nschain);
        }
        if (pragmas.Count > 0) { foreach (var str in pragmas) cb.AppendLine(str); cb.AppendLine(); }
        if (usings.Count > 0) { foreach (var str in usings) cb.AppendLine(str); cb.AppendLine(); }

        // Namespaces, for simplicity we pick the first one...
        // LOW: process all namespaces in TypeNode.EmitParentsFromSyntaxNodes
        var num = 0;
        var item = syntaxes.First();
        var ichain = item.GetChain().Where(static x => x is BaseNamespaceDeclarationSyntax);
        foreach (var ns in ichain)
        {
            var name = ((BaseNamespaceDeclarationSyntax)ns).Name.ToString();
            cb.AppendLine($"namespace {name}");
            cb.AppendLine("{");
            cb.IndentLevel++;

            EmitNamespaceUsings((BaseNamespaceDeclarationSyntax)ns, cb);
            num++;
        }

        // Emitting parent types...
        num += EmitContainingTypes(symbol, cb);
        return num;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the containing types of the given one. Returns the number of opened levels
    /// that must be closed afterwards.
    /// </summary>
    static int EmitContainingTypes(INamedTypeSymbol symbol, CodeBuilder cb)
    {
        var tpchain = symbol.GetChain().Where(static x => x is INamedTypeSymbol);
        var num = 0;

        foreach (var tp in tpchain)
        {
            var type = (INamedTypeSymbol)tp;
            var head = GetTypeHeader(type);

            cb.AppendLine(head);
            cb.AppendLine("{");
            cb.IndentLevel++;
            num++;
        }
        return num;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to populate the list of file-level pragmas using the given syntax chain.
    /// </summary>
    static void PopulateFileLevelPragmas(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            if (ns.SyntaxTree.TryGetText(out var text))
            {
                foreach (var line in text.Lines)
                {
                    var str = line.ToString().Trim();
                    if (str.StartsWith("#pragma")) { if (!items.Contains(str)) items.Add(str); }
                    else if (str.Length != 0) break;
                }
            }
        }
    }

    /// <summary>
    /// Invoked to populate the given list of file-level usings using the given syntax chain.
    /// </summary>
    static void PopulateFileLevelUsings(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            var comp = GetCompilation(ns);
            if (comp is null) continue;

            foreach (var item in comp.Usings)
            {
                var str = item.ToString().Trim();
                if (!string.IsNullOrWhiteSpace(str)) { if (!items.Contains(str)) items.Add(str); }
            }
        }

        // Gets the compilation unit syntax the given syntax node belongs to...
        static CompilationUnitSyntax? GetCompilation(SyntaxNode node)
        {
            while (node is not null)
            {
                if (node is CompilationUnitSyntax comp) return comp;
                node = node.Parent!;
            }
            return null;
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the namespace-level usings on the given code builder.
    /// </summary>
    static void EmitNamespaceUsings(BaseNamespaceDeclarationSyntax syntax, CodeBuilder cb)
    {
        List<string> items = []; foreach (var item in syntax.Usings)
        {
            var str = item.ToString().Trim();
            if (!string.IsNullOrWhiteSpace(str) && !items.Contains(str)) items.Add(str);
        }

        if (items.Count > 0)
        {
            foreach (var str in items) cb.AppendLine(str);
            cb.AppendLine();
        }
    }
}