namespace Yotei.Tools.Generators.Shared;

// ========================================================
/// <summary>
/// Represents a source code generation node.
/// </summary>
internal abstract class Node
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="candidate"></param>
    public Node(Candidate candidate)
    {
        Candidate = candidate.ThrowWhenNull(nameof(candidate));
        Symbol = candidate.Symbol;
    }

    /// <summary>
    /// Initializes a new stand-alone instance not associated with any candidate.
    /// </summary>
    /// <param name="symbol"></param>
    public Node(ISymbol symbol) => Symbol = symbol.ThrowWhenNull(nameof(symbol));

    /// <summary>
    /// The candidate this instance is associated with. The value of this property is null if
    /// this instance was not created by a generator when tranforming a syntax node.
    /// </summary>
    public Candidate? Candidate { get; }

    /// <summary>
    /// The symbol this instance is associated with.
    /// </summary>
    public ISymbol Symbol { get; }

    // ----------------------------------------------------

    /// <summary>
    /// Determines if this node is valid for source code generation purposes, or not.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public abstract bool Validate(SourceProductionContext context);

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the actual source code generated by this node, after the namespace and
    /// type hierarchy up to the tail type has been already emitted.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="file"></param>
    public abstract void Print(SourceProductionContext context, FileBuilder file);
}