namespace Yotei.ORM.Relational.FakeDB;

// ========================================================
public static partial class DB
{
    /// <summary>
    /// The authoritative list of elements.
    /// </summary>
    public static ImmutableList<EmployeeTalentDTO> EmployeeTalents
    {
        get
        {
            if (_EmployeeTalents == null)
            {
                _EmployeeTalents = _EmployeeTalentsShort.ToImmutableList();

                if (IsLongDatabase)
                    _EmployeeTalents = _EmployeeTalents.AddRange(_EmployeeTalentsLong);
            }
            return _EmployeeTalents;
        }
    }

    static ImmutableList<EmployeeTalentDTO> _EmployeeTalents = null!;

    readonly static EmployeeTalentDTO[] _EmployeeTalentsShort = new[]
    {
        new EmployeeTalentDTO() { EmployeeId = "1001", TalentId = "hr" }
        ,new EmployeeTalentDTO() { EmployeeId = "1001", TalentId = "sales" }
        ,new EmployeeTalentDTO() { EmployeeId = "1002", TalentId = "mktg" }
        ,new EmployeeTalentDTO() { EmployeeId = "2001", TalentId = "sales" }
        ,new EmployeeTalentDTO() { EmployeeId = "2002", TalentId = "sales" }
        ,new EmployeeTalentDTO() { EmployeeId = "2002", TalentId = "mktg" }
        ,new EmployeeTalentDTO() { EmployeeId = "2003", TalentId = "tech" }
        ,new EmployeeTalentDTO() { EmployeeId = "2003", TalentId = "hr" }
        ,new EmployeeTalentDTO() { EmployeeId = "2009", TalentId = "tech" }
        ,new EmployeeTalentDTO() { EmployeeId = "2006", TalentId = "tech" }
        ,new EmployeeTalentDTO() { EmployeeId = "2006", TalentId = "hr" }
        ,new EmployeeTalentDTO() { EmployeeId = "2010", TalentId = "tech" }
        ,new EmployeeTalentDTO() { EmployeeId = "2010", TalentId = "sales" }
        ,new EmployeeTalentDTO() { EmployeeId = "2011", TalentId = "hr" }
        ,new EmployeeTalentDTO() { EmployeeId = "2007", TalentId = "tech" }
        ,new EmployeeTalentDTO() { EmployeeId = "3001", TalentId = "sales" }
    };

    readonly static EmployeeTalentDTO[] _EmployeeTalentsLong = new[]
    {
        new EmployeeTalentDTO() { EmployeeId = "4001", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4004", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4005", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4006", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4007", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4009", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4010", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4013", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4016", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4019", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4020", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4026", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4029", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4030", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4031", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4032", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4035", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4037", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4039", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4040", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4041", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4042", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4043", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4044", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4047", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4050", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4051", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4052", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4055", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4059", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4060", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4062", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4066", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4067", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4077", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4078", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4081", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4082", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4083", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4084", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4085", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4089", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4090", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4092", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4093", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4098", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4099", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4106", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4108", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4110", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4111", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4112", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4113", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4114", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4115", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4119", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4120", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4123", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4133", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4136", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4141", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4142", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4143", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4145", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4147", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4148", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4150", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4151", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4154", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4155", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4156", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4158", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4160", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4161", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4162", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4167", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4168", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4171", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4172", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4173", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4174", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4180", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4182", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4185", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4189", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4192", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4194", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4195", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4197", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4198", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4203", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4205", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4207", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4212", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4213", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4219", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4225", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4226", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4231", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4234", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4236", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4239", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4245", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4246", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4256", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4258", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4260", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4264", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4265", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4269", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4270", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4272", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4273", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4274", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4280", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4284", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4286", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4287", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4288", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4290", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4291", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4292", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4293", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4305", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4310", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4311", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4315", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4316", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4319", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4322", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4325", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4327", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4328", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4332", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4334", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4336", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4337", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4342", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4343", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4355", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4357", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4359", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4360", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4361", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4363", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4366", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4367", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4369", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4370", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4371", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4375", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4376", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4377", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4378", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4379", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4380", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4383", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4384", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4385", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4387", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4390", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4391", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4393", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4396", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4399", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4400", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4402", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4405", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4408", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4409", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4410", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4412", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4413", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4414", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4419", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4420", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4423", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4425", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4431", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4433", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4434", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4435", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4436", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4442", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4445", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4446", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4447", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4449", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4451", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4456", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4458", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4465", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4471", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4473", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4474", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4477", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4480", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4482", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4483", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4484", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4485", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4487", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4489", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4492", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4497", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4504", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4505", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4518", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4519", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4522", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4523", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4524", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4525", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4526", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4532", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4534", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4536", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4538", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4543", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4545", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4546", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4550", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4551", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4559", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4562", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4563", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4564", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4565", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4567", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4568", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4572", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4573", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4574", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4578", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4580", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4581", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4584", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4588", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4591", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4594", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4595", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4598", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4600", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4603", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4605", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4607", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4608", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4610", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4611", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4614", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4618", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4620", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4622", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4623", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4624", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4628", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4630", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4633", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4634", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4635", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4640", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4643", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4646", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4647", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4648", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4650", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4652", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4655", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4656", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4658", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4659", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4660", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4662", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4664", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4666", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4667", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4669", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4671", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4672", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4673", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4679", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4682", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4686", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4687", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4688", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4693", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4694", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4696", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4698", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4699", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4705", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4713", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4716", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4717", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4725", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4726", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4731", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4739", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4743", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4747", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4750", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4751", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4752", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4755", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4756", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4757", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4758", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4759", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4760", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4761", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4762", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4766", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4768", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4774", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4776", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4778", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4779", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4780", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4781", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4790", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4794", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4797", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4799", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4803", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4804", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4808", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4809", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4813", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4815", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4816", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4822", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4824", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4825", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4828", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4830", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4831", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4832", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4836", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4839", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4841", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4844", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4850", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4851", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4852", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4855", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4861", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4863", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4864", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4865", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4868", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4871", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4872", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4880", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4884", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4886", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4897", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4900", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4906", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4908", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4910", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4912", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4916", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4918", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4919", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4925", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4927", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4929", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4933", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4934", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4935", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4937", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4938", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4939", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4940", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4950", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4956", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4959", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4960", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4961", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4963", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4964", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4965", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4967", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4969", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4970", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4971", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4973", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4974", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4975", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4976", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4977", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4987", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4989", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "4990", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4991", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "4993", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "4999", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5000", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5001", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5002", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5003", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5004", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5012", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5013", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5014", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5015", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5016", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5017", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5021", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5023", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5026", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5027", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5031", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5032", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5033", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5036", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5037", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5041", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5042", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5043", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5045", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5049", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5052", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5053", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5059", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5061", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5064", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5065", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5071", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5073", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5075", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5076", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5077", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5082", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5084", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5085", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5087", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5088", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5089", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5090", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5091", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5095", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5100", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5105", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5113", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5115", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5116", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5118", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5120", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5122", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5128", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5129", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5130", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5133", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5134", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5136", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5137", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5138", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5139", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5148", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5150", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5151", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5159", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5161", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5166", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5167", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5170", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5171", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5172", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5174", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5175", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5177", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5180", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5181", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5182", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5183", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5184", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5185", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5186", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5188", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5189", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5191", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5193", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5195", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5196", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5197", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5199", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5202", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5204", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5207", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5208", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5209", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5210", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5213", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5215", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5218", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5225", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5226", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5227", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5229", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5230", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5232", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5234", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5235", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5236", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5237", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5239", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5240", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5242", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5245", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5248", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5254", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5257", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5258", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5260", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5262", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5265", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5266", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5271", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5274", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5275", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5278", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5279", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5283", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5285", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5286", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5287", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5288", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5289", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5292", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5293", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5295", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5297", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5298", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5301", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5304", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5310", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5311", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5313", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5314", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5316", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5317", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5318", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5319", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5320", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5321", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5322", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5328", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5329", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5332", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5334", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5335", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5338", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5340", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5343", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5345", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5347", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5350", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5353", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5355", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5356", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5357", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5359", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5360", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5364", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5367", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5368", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5369", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5370", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5374", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5376", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5377", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5379", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5380", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5381", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5383", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5384", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5386", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5387", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5389", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5391", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5394", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5396", TalentId = "sales" }
        , new EmployeeTalentDTO() { EmployeeId = "5399", TalentId = "tech" }
        , new EmployeeTalentDTO() { EmployeeId = "5400", TalentId = "mktg" }
        , new EmployeeTalentDTO() { EmployeeId = "5401", TalentId = "sales" }
    };
}