namespace Yotei.Generators.Tree;

// ========================================================
/// <summary>
/// <inheritdoc cref="IFileNode"/>
/// </summary>
internal class FileNode : IFileNode
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="generator"></param>
    /// <param name="name"></param>
    public FileNode(IGenerator generator, string name)
    {
        Generator = generator.ThrowIfNull(nameof(generator));
        Name = name.NotNullNotEmpty(nameof(name));
    }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns><inheritdoc/></returns>
    public override string ToString() => $"File: {Name}";

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public IGenerator Generator { get; }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public INode? Parent => null;

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public string Name { get; }

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public IEnumerable<INamespaceNode> ChildNamespaces => _ChildNamespaces;
    readonly List<INamespaceNode> _ChildNamespaces = new();

    INamespaceNode LocateNamespace(ICaptured captured)
    {
        var type = captured.AsCapturedType();
        var nsSyntax = type.NamespaceSyntaxChain[0];
        var nsName = nsSyntax.Name.LongName();

        var node = _ChildNamespaces.Find(x => x.Name == nsName);
        if (node == null)
        {
            node = new NamespaceNode(this, nsSyntax);
            _ChildNamespaces.Add(node);
        }
        return node;
    }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public void Register(ICaptured captured)
    {
        captured = captured.ThrowIfNull(nameof(captured));

        var node = LocateNamespace(captured);
        node.Register(captured, 1, 0);
    }

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns><inheritdoc/></returns>
    public bool Validate(SourceProductionContext context)
    {
        foreach (var node in ChildNamespaces) if (!node.Validate(context)) return false;
        return true;
    }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public void Print(SourceProductionContext context, CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine("#nullable enable");
        PrintUsings(cb);
        cb.AppendLine();

        foreach (var node in ChildNamespaces) node.Print(context, cb);

        var name = Name + ".g.cs";
        var code = cb.ToString();
        context.AddSource(name, code);
    }

    /// <summary>
    /// Appends file-level usings.
    /// </summary>
    /// <param name="cb"></param>
    void PrintUsings(CodeBuilder cb)
    {
        var list = new NoDuplicatesList<string>(
            comparer: StringComparer.Ordinal,
            validator: x => x.NotNullNotEmpty("using"));

        foreach (var item in ChildNamespaces)
        {
            var comp = GetCompilation(item.Syntax);
            if (comp != null)
            {
                foreach (var temp in comp.Usings) list.Add(temp.Name.ToString());
            }
        }

        if (list.Count > 0)
        {
            cb.AppendLine();
            foreach (var item in list) cb.AppendLine($"using {item};");
        }

        // Gets the compilation unit for the given namespace...
        static CompilationUnitSyntax? GetCompilation(BaseNamespaceDeclarationSyntax syntax)
        {
            SyntaxNode? node = syntax;
            while (node != null)
            {
                if (node is CompilationUnitSyntax comp) return comp;
                node = node.Parent;
            }

            return null;
        }
    }
}