namespace Yotei.Tools.CoreGenerator;

// ========================================================
/// <summary>
/// Represents a type-alike node in the source code generation hierarchy.
/// </summary>
internal class TypeNode : INode
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="symbol"></param>
    [SuppressMessage("", "IDE0290")]
    public TypeNode(INamedTypeSymbol symbol) => Symbol = symbol;

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns></returns>
    public override string ToString() => $"Type: {Symbol.Name}";

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc cref="INode.Symbol"/>
    /// </summary>
    public INamedTypeSymbol Symbol { get; }
    ISymbol INode.Symbol => Symbol;

    /// <summary>
    /// Determines if this instance has been created by the generator to hold the host of its
    /// found members. If not, it is assumed the type was found by itself.
    /// </summary>
    public bool IsAutoGenerated { get; init; }

    /// <summary>
    /// The collection of syntax nodes where the element represented by this instance was found.
    /// </summary>
    public List<TypeDeclarationSyntax> SyntaxNodes { get; } = [];

    /// <summary>
    /// The collection of attributes captured for the element represented by this instance, at the
    /// syntax nodes where it was found.
    /// </summary>
    public List<AttributeData> Attributes { get; } = [];

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc cref="INode.Augment(ICandidate)"/>
    /// </summary>
    /// <param name="candidate"></param>
    public virtual void Augment(TypeCandidate candidate)
    {
        if (candidate.Syntax != null) SyntaxNodes.Add(candidate.Syntax);
        Attributes.AddRange(candidate.Attributes);
    }
    void INode.Augment(ICandidate candidate) => Augment((TypeCandidate)candidate);

    /// <summary>
    /// <inheritdoc cref="INode.Augment(INode)"/>
    /// </summary>
    /// <param name="node"></param>
    public virtual void Augment(TypeNode node)
    {
        SyntaxNodes.AddRange(node.SyntaxNodes);
        Attributes.AddRange(node.Attributes);
        ChildProperties.AddRange(node.ChildProperties);
        ChildFields.AddRange(node.ChildFields);
        ChildMethods.AddRange(node.ChildMethods);
    }
    void INode.Augment(INode node) => Augment((TypeNode)node);

    // ----------------------------------------------------

    /// <summary>
    /// The collection of child properties registered into this instance.
    /// </summary>
    public List<PropertyNode> ChildProperties { get; } = [];

    /// <summary>
    /// The collection of child fields registered into this instance.
    /// </summary>
    public List<FieldNode> ChildFields { get; } = [];

    /// <summary>
    /// The collection of child methods registered into this instance.
    /// </summary>
    public List<MethodNode> ChildMethods { get; } = [];

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public virtual bool Validate(SourceProductionContext context) => throw null;

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    public virtual void Emit(SourceProductionContext context, CodeBuilder cb) => throw null;
}