#pragma warning disable CS9264

namespace Yotei.Tools.CoreGenerator;

// ========================================================
/// <summary>
/// Represents a type-alike node in the source code generation hierarchy.
/// </summary>
internal class TypeNode : ITreeNode
{
    /// <summary>
    /// Initializes a new instance.
    /// <br/> The '<see cref="Parent"/>' property *MUST* be set before using this instance.
    /// </summary>
    /// <param name="symbol"></param>
    [SuppressMessage("", "IDE0290")]
    public TypeNode(INamedTypeSymbol symbol) => Symbol = symbol.ThrowWhenNull();

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns></returns>
    public override string ToString() => $"Type: {Symbol.EasyName()}";

    // ----------------------------------------------------

    /// <summary>
    /// Determines if this instance was created by the generator to hold the members found for
    /// this type. If not, then this instance was created because the type itself was identified
    /// as a potential candidate.
    /// </summary>
    public bool IsAutoGenerated { get; init; }

    /// <summary>
    /// <inheritdoc cref="ITreeNode.Parent"/>
    /// </summary>
    public FileNode Parent { get; set => field = value.ThrowWhenNull(); }
    INode ITreeNode.Parent => Parent;

    /// <summary>
    /// <inheritdoc cref="ITreeNode.Symbol"/>
    /// </summary>
    public INamedTypeSymbol Symbol { get; }
    ISymbol ITreeNode.Symbol => Symbol;

    /// <summary>
    /// The syntax nodes captured for this instance, or an empty collection if this information
    /// was not captured.
    /// </summary>
    public List<TypeDeclarationSyntax> SyntaxNodes { get; } = [];

    /// <summary>
    /// The attributes by which this instance was found, or an empty collection if this information
    /// was not captured.
    /// </summary>
    public List<AttributeData> Attributes { get; } = [];

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc <see cref="ITreeNode.Augment(IValidCandidate)"/>/>
    /// </summary>
    /// <param name="candidate"></param>
    public virtual void Augment(TypeCandidate candidate)
    {
        if (candidate.Syntax != null)
            if (SyntaxNodes.Find(x => x.IsEquivalentTo(candidate.Syntax)) == null)
                SyntaxNodes.Add(candidate.Syntax);

        foreach (var at in candidate.Attributes)
            if (Attributes.Find(x => x.EqualTo(at)) == null)
                Attributes.Add(at);
    }
    void ITreeNode.Augment(IValidCandidate candidate) => Augment((TypeCandidate)candidate);

    /// <summary>
    /// <inheritdoc cref="ITreeNode.Augment(ITreeNode)"/>
    /// </summary>
    /// <param name="node"></param>
    public virtual void Augment(TypeNode node)
    {
        foreach (var syntax in node.SyntaxNodes)
            if (SyntaxNodes.Find(x => x.IsEquivalentTo(syntax)) == null)
                SyntaxNodes.Add(syntax);

        foreach (var at in node.Attributes)
            if (Attributes.Find(x => x.EqualTo(at)) == null)
                Attributes.Add(at);

        foreach (var item in node.ChildProperties)
            if (!ChildProperties.Contains(item)) ChildProperties.Add(item);

        foreach (var item in node.ChildFields)
            if (!ChildFields.Contains(item)) ChildFields.Add(item);

        foreach (var item in node.ChildMethods)
            if (!ChildMethods.Contains(item)) ChildMethods.Add(item);
    }
    void ITreeNode.Augment(ITreeNode node) => Augment((TypeNode)node);

    // ----------------------------------------------------

    /// <summary>
    /// The collection of child property-alike nodes known to this instance.
    /// </summary>
    public List<PropertyNode> ChildProperties { get; } = [];

    /// <summary>
    /// The collection of child field-alike nodes known to this instance.
    /// </summary>
    public List<FieldNode> ChildFields { get; } = [];

    /// <summary>
    /// The collection of child method-alike nodes known to this instance.
    /// </summary>
    public List<MethodNode> ChildMethods { get; } = [];

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public virtual bool Validate(SourceProductionContext context)
    {
        if (Symbol.IsPartial) { Symbol.ReportError(TreeError.TypeNotPartial, context); return false; }
        if (!IsSupportedKind()) { Symbol.ReportError(TreeError.KindNotSupported, context); return false; }

        foreach (var node in ChildProperties) if (!node.Validate(context)) return false;
        foreach (var node in ChildFields) if (!node.Validate(context)) return false;
        foreach (var node in ChildMethods) if (!node.Validate(context)) return false;

        return true;
    }

    /// <summary>
    /// Determines if this type's kind is supported for code generation.
    /// </summary>
    /// <returns></returns>
    protected virtual bool IsSupportedKind() => Symbol.TypeKind is
        TypeKind.Class or
        TypeKind.Struct or
        TypeKind.Interface;

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    public virtual void Emit(SourceProductionContext context, CodeBuilder cb)
    {
        var head = GetHeader(context);
        cb.AppendLine(head);

        cb.AppendLine("{");
        cb.IndentLevel++;
        {
            var old = cb.Length; EmitCore(context, cb);
            var len = cb.Length; if (old != len) cb.AppendLine();
            EmitChilds(context, cb);
        }
        cb.IndentLevel--;
        cb.AppendLine("}");
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to obtain the type's header. By default this method returns a string with the
    /// 'partial Name' format. Inheritors can then add a base list ('... : TBase, IFace, ...)
    /// as needed.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    protected virtual string GetHeader(SourceProductionContext context)
    {
        var rec = Symbol.IsRecord ? "record " : string.Empty;

        string kind;
        switch (Symbol.TypeKind)
        {
            case TypeKind.Class: kind = "class"; break;
            case TypeKind.Struct: kind = "struct"; break;
            case TypeKind.Interface: kind = "interface"; break;

            default:
                var diag = Symbol.ReportError(TreeError.KindNotSupported, context);
                throw new ArgumentException(diag.GetMessage());
        }

        var name = Symbol.EasyName();
        return $"partial {rec}{kind} {name}";
    }

    /// <summary>
    /// Invoked to emit the core contents of this type.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    protected virtual void EmitCore(SourceProductionContext context, CodeBuilder cb) { }

    /// <summary>
    /// Invoked to emit the source code of the captured child nodes, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    protected virtual void EmitChilds(SourceProductionContext context, CodeBuilder cb)
    {
        var nl = false;

        foreach (var node in ChildFields)
        {
            if (nl) cb.AppendLine(); nl = true;
            node.Emit(context, cb);
        }
        foreach (var node in ChildProperties)
        {
            if (nl) cb.AppendLine(); nl = true;
            node.Emit(context, cb);
        }
        foreach (var node in ChildMethods)
        {
            if (nl) cb.AppendLine(); nl = true;
            node.Emit(context, cb);
        }
    }
}