namespace Yotei.Tools.CoreGenerator;

// ========================================================
/// <summary>
/// Represents a type-alike node in the source code generation hierarchy.
/// </summary>
internal class TypeNode : INode
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="symbol"></param>
    [SuppressMessage("", "IDE0290")]
    public TypeNode(INamedTypeSymbol symbol) => Symbol = symbol;

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns></returns>
    public override string ToString() => $"Type: {Symbol.Name}";

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc cref="INode.Symbol"/>
    /// </summary>
    public INamedTypeSymbol Symbol { get; }
    ISymbol INode.Symbol => Symbol;

    /// <summary>
    /// Determines if this instance has been created by the generator to hold the host of its
    /// found members. If not, it is assumed the type was found by itself.
    /// </summary>
    public bool IsAutoGenerated { get; init; }

    /// <summary>
    /// The collection of syntax nodes where the element represented by this instance was found.
    /// </summary>
    public List<TypeDeclarationSyntax> SyntaxNodes { get; } = [];

    /// <summary>
    /// The collection of attributes captured for the element represented by this instance, at the
    /// syntax nodes where it was found.
    /// </summary>
    public List<AttributeData> Attributes { get; } = [];

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc cref="INode.Augment(ICandidate)"/>
    /// </summary>
    /// <param name="candidate"></param>
    public virtual void Augment(TypeCandidate candidate)
    {
        if (candidate.Syntax != null) SyntaxNodes.Add(candidate.Syntax);
        Attributes.AddRange(candidate.Attributes);
    }
    void INode.Augment(ICandidate candidate) => Augment((TypeCandidate)candidate);

    /// <summary>
    /// <inheritdoc cref="INode.Augment(INode)"/>
    /// </summary>
    /// <param name="node"></param>
    public virtual void Augment(TypeNode node)
    {
        SyntaxNodes.AddRange(node.SyntaxNodes);
        Attributes.AddRange(node.Attributes);
        ChildProperties.AddRange(node.ChildProperties);
        ChildFields.AddRange(node.ChildFields);
        ChildMethods.AddRange(node.ChildMethods);
    }
    void INode.Augment(INode node) => Augment((TypeNode)node);

    // ----------------------------------------------------

    /// <summary>
    /// The collection of child properties registered into this instance.
    /// </summary>
    public List<PropertyNode> ChildProperties { get; } = [];

    /// <summary>
    /// The collection of child fields registered into this instance.
    /// </summary>
    public List<FieldNode> ChildFields { get; } = [];

    /// <summary>
    /// The collection of child methods registered into this instance.
    /// </summary>
    public List<MethodNode> ChildMethods { get; } = [];

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/> This method also validates, in cascade, its child nodes, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public virtual bool Validate(SourceProductionContext context)
    {
        if (!Symbol.IsPartial) { Symbol.ReportError(TreeError.TypeNotPartial, context); return false; }
        if (!IsSupportedKind()) { Symbol.ReportError(TreeError.KindNotSupported, context); return false; }

        foreach (var node in ChildProperties) if (!node.Validate(context)) return false;
        foreach (var node in ChildFields) if (!node.Validate(context)) return false;
        foreach (var node in ChildMethods) if (!node.Validate(context)) return false;

        return true;
    }

    /// <summary>
    /// Determines if this type's kind is supported for code generation.
    /// </summary>
    /// <returns></returns>
    protected virtual bool IsSupportedKind() => Symbol.TypeKind is
        TypeKind.Class or
        TypeKind.Struct or
        TypeKind.Interface;

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/> This method emits the type's header, its core contents, and then in cascade
    /// the source code of its child nodes, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    public virtual void Emit(SourceProductionContext context, CodeBuilder cb)
    {
        var head = GetHeader(context);
        cb.AppendLine(head);
        
        cb.AppendLine("{");
        cb.IndentLevel++;
        {
            var old = cb.Length; EmitCore(context, cb);            
            var len = cb.Length; if (old != len) cb.AppendLine();
            EmitChilds(context, cb);
        }
        cb.IndentLevel--;
        cb.AppendLine("}");
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to obtain the type's header. By default this method returns a string with the
    /// 'partial Name' format. Inheritors can then add a base list ('... : TBase, IFace, ...)
    /// as needed.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    protected virtual string GetHeader(SourceProductionContext context)
    {
        var rec = Symbol.IsRecord ? "record " : string.Empty;

        string kind;
        switch (Symbol.TypeKind)
        {
            case TypeKind.Class: kind = "class"; break;
            case TypeKind.Struct: kind = "struct"; break;
            case TypeKind.Interface: kind = "interface"; break;

            default:
                var diag = Symbol.ReportError(TreeError.KindNotSupported, context);
                throw new ArgumentException(diag.GetMessage());
        }

        //var options = xxx;
        //var name = Symbol.EasyName(options);
        //return $"partial {rec}{kind} {name}";

        // HIGH: terminar GetGeader()
        throw null;
    }

    /// <summary>
    /// Invoked to emit the core contents of this type.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    protected virtual void EmitCore(SourceProductionContext context, CodeBuilder cb) { }

    /// <summary>
    /// Invoked to emit the source code of the captured child nodes, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    protected virtual void EmitChilds(SourceProductionContext context, CodeBuilder cb)
    {
        var nl = false;

        foreach (var node in ChildFields)
        {
            if (nl) cb.AppendLine(); nl = true;
            node.Emit(context, cb);
        }
        foreach (var node in ChildProperties)
        {
            if (nl) cb.AppendLine(); nl = true;
            node.Emit(context, cb);
        }
        foreach (var node in ChildMethods)
        {
            if (nl) cb.AppendLine(); nl = true;
            node.Emit(context, cb);
        }
    }
}