namespace Yotei.Tools.TreeGenerator;

// ========================================================
partial class TypeNode
{
    /// <summary>
    /// <inheritdoc/>
    /// <br/> This implementation is not a virtual one, and shall not be overriden. Customization
    /// is achieved through the specific protected methods.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    /// <returns></returns>
    public bool Emit(SourceProductionContext context, CodeBuilder cb)
    {
        if (!OnValidate(context)) return false;

        var num = PrintAllParents(cb);

        var head = GetTypeHeader(Symbol);
        var str = GetBaseList();
        if (str != null) head += $" : {str}";

        cb.AppendLine(head);
        cb.AppendLine("{");
        cb.IndentLevel++;

        var old = cb.Length;
        var r = OnEmitCore(context, cb);
        if (r)
        {
            var len = cb.Length; if (old != len) cb.AppendLine();
            if (!OnEmitChilds(context, cb)) r = false;
        }
        cb.IndentLevel--;
        cb.AppendLine("}");

        for (int i = 0; i < num; i++)
        {
            cb.IndentLevel--;
            cb.AppendLine("}");
        }
        return r;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to print the namespaces and containing types of this one. Returns the number of
    /// indentation levels emitted in the out argument, so they can be decreased afterwards.
    /// </summary>
    int PrintAllParents(CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();

        return SyntaxNodes.Count == 0 ? EmitFromSymbol() : EmitFromSyntaxes();

        /// <summary>
        /// Invoked to emit the namespaces and containing types when there are no syntax nodes
        /// available.
        /// </summary>
        int EmitFromSymbol()
        {
            // In this we can only emit a compound namespace...
            var nschain = Symbol.GetElementChain().Where(static x => x is INamespaceSymbol);
            var name = string.Join(".", nschain.Select(x => x.Name));

            cb.AppendLine($"namespace {name}");
            cb.AppendLine("{");
            cb.IndentLevel++;

            // Finishing...
            var num = 1 + PrintTypeParents(cb);
            return num;
        }

        /// <summary>
        /// Invoked to emit the namespaces and containing types when there are known syntax nodes.
        /// </summary>
        int EmitFromSyntaxes()
        {
            // Emitting file-level pragmas and usings...
            List<string> pragmas = [];
            List<string> usings = [];

            foreach (var syntax in SyntaxNodes)
            {
                var nschain = syntax
                    .GetElementChain()
                    .Where(static x => x is BaseNamespaceDeclarationSyntax);

                PopulateFileLevelPragmas(pragmas, nschain);
                PopulateFileLevelUsings(usings, nschain);
            }

            if (pragmas.Count > 0) { foreach (var str in pragmas) cb.AppendLine(str); cb.AppendLine(); }
            if (usings.Count > 0) { foreach (var str in usings) cb.AppendLine(str); cb.AppendLine(); }

            // Emitting namespaces...
            var num = 0;
            foreach (var syntax in SyntaxNodes)
            {
                var nschain = syntax
                    .GetElementChain()
                    .Where(static x => x is BaseNamespaceDeclarationSyntax);

                foreach (var ns in nschain)
                {
                    var nspace = (BaseNamespaceDeclarationSyntax)ns;
                    var name = nspace.Name.ToString();
                    cb.AppendLine($"namespace {name}");
                    cb.AppendLine("{");
                    cb.IndentLevel++;

                    PrintNamespaceUsings(nspace, cb);
                    num++;
                }
            }

            // Finishing...
            num += PrintTypeParents(cb);
            return num;
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the containing types of this one. Returns the number of indentation
    /// levels emitted in the out argument, so they can be decreased afterwards.
    /// </summary>
    int PrintTypeParents(CodeBuilder cb)
    {
        var tpchain = Symbol.GetElementChain().Where(static x => x is INamedTypeSymbol).ToList();
        tpchain = tpchain.GetRange(0, tpchain.Count - 1);

        for (int i = 0; i < tpchain.Count; i++)
        {
            var type = (INamedTypeSymbol)tpchain[i];
            var head = GetTypeHeader(type);

            cb.AppendLine(head);
            cb.AppendLine("{");
            cb.IndentLevel++;
        }

        return tpchain.Count;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Involed to populate the given collection of file-level pragmas, using the elements in
    /// the given chain.
    /// </summary>
    static void PopulateFileLevelPragmas(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            if (ns.SyntaxTree.TryGetText(out var text))
            {
                foreach (var line in text.Lines)
                {
                    var str = line.ToString().Trim();
                    if (str.StartsWith("#pragma") && !items.Contains(str)) items.Add(str);
                    else if (str.StartsWith("namespace")) break;
                }
            }
        }
    }

    /// <summary>
    /// Involed to populate the given collection of file-level usings, using the elements in
    /// the given chain.
    /// </summary>
    static void PopulateFileLevelUsings(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            var comp = GetCompilation(ns);
            if (comp is null) continue;

            foreach (var item in comp.Usings)
            {
                var str = item.ToString().Trim();
                if (!string.IsNullOrWhiteSpace(str) && !items.Contains(str)) items.Add(str);
            }
        }

        // Gets the compilation unit syntax the given syntax node belongs to...
        static CompilationUnitSyntax? GetCompilation(SyntaxNode node)
        {
            while (node is not null)
            {
                if (node is CompilationUnitSyntax comp) return comp;
                node = node.Parent!;
            }
            return null;
        }
    }


    // ----------------------------------------------------

    /// <summary>
    /// Invoked to **emit** the usings found at the given namespace's level.
    /// </summary>
    /// <param name="ns"></param>
    /// <param name="cb"></param>
    static void PrintNamespaceUsings(BaseNamespaceDeclarationSyntax ns, CodeBuilder cb)
    {
        List<string> items = []; foreach (var item in ns.Usings)
        {
            var str = item.ToString().Trim();
            if (!string.IsNullOrWhiteSpace(str) && !items.Contains(str)) items.Add(str);
        }

        if (items.Count > 0)
        {
            foreach (var str in items) cb.AppendLine(str);
            cb.AppendLine();
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// Returns an appropriate header for the given type.
    /// </summary>
    /// <param name="symbol"></param>
    /// <returns></returns>
    static string GetTypeHeader(INamedTypeSymbol symbol)
    {
        var rec = symbol.IsRecord ? "record " : string.Empty;
        string kind = symbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => throw new ArgumentException("Type kind not supported.").WithData(symbol.Name)
        };

        // We'll assume the type is "in range", so a simplified name is enough...
        var name = symbol.EasyName(new()
        {
            UseSpecialNames = true,
            NullableStyle = EasyNullableStyle.UseAnnotations,
            GenericStyle = EasyGenericStyle.UseEasyNames,
        });
        return $"partial {rec}{kind} {name}";
    }
}