namespace Yotei.Tools.Generators;

// ========================================================
partial class TypeNode
{
    /// <summary>
    /// Obtains the appropriate header for the given type.
    /// </summary>
    /// <param name="symbol"></param>
    /// <returns></returns>
    static string GetTypeHeader(INamedTypeSymbol symbol)
    {
        var rec = symbol.IsRecord ? "record " : string.Empty;
        var kind = symbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => throw new ArgumentException("Type kind not supported.").WithData(symbol)
        };

        // We assume the type "is in range", so a simplified name is enough...
        var name = symbol.EasyName(new()
        {
            UseSpecialNames = true,
            NullableStyle = EasyNullableStyle.UseAnnotations,
            GenericListStyle = EasyGenericListStyle.UseNames,
        });

        // Always a partial one...
        return $"partial {rec}{kind} {name}";
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the host parents of this instance. Returns the number of opened levels
    /// that must be closed afterwards.
    /// </summary>
    int OnEmitParents(ref TreeContext context, CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();

        return SyntaxNodes.Count == 0
            ? OnEmitParentsFromSymbol(ref context, cb)
            : OnEmitParentsFromSyntaxNodes(ref context, cb);
    }

    /// <summary>
    /// Invoked to emit the host declaring containers from the captured symbol, which is the
    /// fall back when no syntax nodes are captured.
    /// </summary>
    int OnEmitParentsFromSymbol(ref TreeContext context, CodeBuilder cb)
    {
        var nschain = Symbol.GetChain().Where(static x => x is INamespaceSymbol);
        var name = string.Join(".", nschain.Select(x => x.Name));

        // The most we can do here is to combine the namespace...
        cb.AppendLine($"namespace {name}");
        cb.AppendLine("{");
        cb.IndentLevel++;

        // Emitting parent types...
        var num = OnEmitTypeParents(cb);
        return num + 1;
    }

    /// <summary>
    /// Invoked to emit the host declaring containers from the captured syntax nodes, which is
    /// the richest way.
    /// </summary>
    int OnEmitParentsFromSyntaxNodes(ref TreeContext context, CodeBuilder cb)
    {
        List<string> pragmas = [];
        List<string> usings = [];

        // File-level pragmas and usings...
        foreach (var syntax in SyntaxNodes)
        {
            var nschain = syntax.GetChain().Where(static x => x is BaseNamespaceDeclarationSyntax);
            PopulateFileLevelPragmas(pragmas, nschain);
            PopulateFileLevelUsings(usings, nschain);
        }
        if (pragmas.Count > 0) { foreach (var str in pragmas) cb.AppendLine(str); cb.AppendLine(); }
        if (usings.Count > 0) { foreach (var str in usings) cb.AppendLine(str); cb.AppendLine(); }

        // Namespaces...
        var num = 0;
        foreach (var syntax in SyntaxNodes)
        {
            var nschain = syntax.GetChain().Where(static x => x is BaseNamespaceDeclarationSyntax);
            foreach (var ns in nschain)
            {
                var name = ((BaseNamespaceDeclarationSyntax)ns).Name.ToString();
                cb.AppendLine($"namespace {name}");
                cb.AppendLine("{");
                cb.IndentLevel++;

                OnEmitNamespaceUsings((BaseNamespaceDeclarationSyntax)ns, cb);
                num++;
            }
        }

        // Emitting parent types...
        num += OnEmitTypeParents(cb);
        return num;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the containing types of this one. Returns the number of opened levels that
    /// must be closed afterwards.
    /// </summary>
    int OnEmitTypeParents(CodeBuilder cb)
    {
        var tpchain = Symbol.GetChain().Where(static x => x is INamedTypeSymbol);
        var num = 0;

        foreach (var tp in tpchain)
        {
            var type = (INamedTypeSymbol)tp;
            var head = GetTypeHeader(type);

            cb.AppendLine(head);
            cb.AppendLine("{");
            cb.IndentLevel++;
            num++;
        }
        return num;
    }

    /// <summary>
    /// Invoked to populate the given list of file-level pragmas.
    /// </summary>
    void PopulateFileLevelPragmas(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            if (ns.SyntaxTree.TryGetText(out var text))
            {
                foreach (var line in text.Lines)
                {
                    var str = line.ToString().Trim();
                    if (str.StartsWith("#pragma")) { if (!items.Contains(str)) items.Add(str); }
                    else if (str.Length != 0) break;
                }
            }
        }
    }

    /// <summary>
    /// Invoked to populate the given list of file-level usings.
    /// </summary>
    void PopulateFileLevelUsings(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            var comp = GetCompilation(ns);
            if (comp is null) continue;

            foreach (var item in comp.Usings)
            {
                var str = item.ToString().Trim();
                if (!string.IsNullOrWhiteSpace(str)) { if (!items.Contains(str)) items.Add(str); }
            }
        }

        // Gets the compilation unit syntax the given syntax node belongs to...
        static CompilationUnitSyntax? GetCompilation(SyntaxNode node)
        {
            while (node is not null)
            {
                if (node is CompilationUnitSyntax comp) return comp;
                node = node.Parent!;
            }
            return null;
        }
    }

    /// <summary>
    /// Invoked to emit the namespace-level usings on the given code builder.
    /// </summary>
    void OnEmitNamespaceUsings(BaseNamespaceDeclarationSyntax syntax, CodeBuilder cb)
    {
        List<string> items = []; foreach (var item in syntax.Usings)
        {
            var str = item.ToString().Trim();
            if (!string.IsNullOrWhiteSpace(str) && !items.Contains(str)) items.Add(str);
        }

        if (items.Count > 0)
        {
            foreach (var str in items) cb.AppendLine(str);
            cb.AppendLine();
        }
    }
}