namespace Yotei.Tools.Generators;

// ========================================================
partial class TypeNode
{
    /// <summary>
    /// Obtains the not-normalized file name of the element carried by this instance. It needs
    /// normalization before it can be used as an actual file name.
    /// </summary>
    public string FileName
    {
        get
        {
            var options = new EasyTypeOptions
            {
                NamespaceStyle = EasyNamespaceStyle.Default,
                UseHost = true,
                UseSpecialNames = true,
                RemoveAttributeSuffix = false,
                NullableStyle = EasyNullableStyle.UseAnnotations,
                GenericListStyle = EasyGenericListStyle.UseNames
            };
            return Symbol.EasyName(options);
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// <br/> This method is INFRASTRUCTURE and not intended for inheritors usage.
    /// <br/> Inheritors can modify behavior by using the <see cref="GetBaseList"/>, the
    /// <see cref="OnValidate(SourceProductionContext)"/>, the <see cref="IsSupportedKind"/>, the
    /// <see cref="OnEmitCore(ref TreeContext, CodeBuilder)"/> and the
    /// <see cref="OnEmitChilds(ref TreeContext, CodeBuilder)"/> methods.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    /// <returns></returns>
    public bool Emit(ref TreeContext context, CodeBuilder cb)
    {
        context.Context.CancellationToken.ThrowIfCancellationRequested();

        // Parent elements, returning how many levels were opened...
        var num = OnEmitParents(ref context, cb);

        // This type...
        var head = GetTypeHeader(Symbol);
        var str = GetBaseList();
        if ((str = str.NullWhenEmpty(trim: true)) != null) head += $" : {str}";

        cb.AppendLine(head);
        cb.AppendLine("{");
        cb.IndentLevel++;

        var old = cb.Length;
        var ret = OnEmitCore(ref context, cb);
        if (ret)
        {
            var len = cb.Length;
            if (len != old) cb.AppendLine();

            if (!OnEmitChilds(ref context, cb)) ret = false;
        }
        cb.IndentLevel--;
        cb.AppendLine("}");

        // Closing he parent levels...
        for (var i = 0; i < num; i++)
        {
            cb.IndentLevel--;
            cb.AppendLine("}");
        }

        // Returning...
        return ret;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Obtains the appropriate header for the given type.
    /// </summary>
    /// <param name="symbol"></param>
    /// <returns></returns>
    static string GetTypeHeader(INamedTypeSymbol symbol)
    {
        var rec = symbol.IsRecord ? "record " : string.Empty;
        var kind = symbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => throw new ArgumentException("Type kind not supported.").WithData(symbol)
        };

        // We assume the type "is in range", so a simplified name is enough...
        var name = symbol.EasyName(new()
        {
            NamespaceStyle = EasyNamespaceStyle.None,
            UseHost = false,
            UseSpecialNames = true,
            RemoveAttributeSuffix = false,
            NullableStyle = EasyNullableStyle.UseAnnotations,
            GenericListStyle = EasyGenericListStyle.UseNames,
        });

        // Always a partial one...
        return $"partial {rec}{kind} {name}";
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the host parents of this instance. Returns the number of opened levels
    /// that must be closed afterwards.
    /// </summary>
    int OnEmitParents(ref TreeContext context, CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();

        return SyntaxNodes.Count == 0
            ? EmitParentsFromSymbol(Symbol, ref context, cb)
            : EmitParentsFromSyntaxNodes(Symbol, SyntaxNodes, ref context, cb);
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit parents when only the symbol is available. This method is considered as a
    /// less-rich or basic fall-back.
    /// </summary>
    static int EmitParentsFromSymbol(
        INamedTypeSymbol symbol, ref TreeContext context, CodeBuilder cb)
    {
        // We may still be able to use syntaxes...
        var references = symbol.DeclaringSyntaxReferences;
        if (references.Length > 0)
        {
            var nodes = references.Select(x => x.GetSyntax()).OfType<BaseTypeDeclarationSyntax>();
            if (nodes.Any()) return EmitParentsFromSyntaxNodes(symbol, nodes, ref context, cb);
        }

        // The fall-back basic way...
        var nschain = symbol.GetChain().Where(static x => x is INamespaceSymbol);
        var name = string.Join(".", nschain.Select(x => x.Name));

        cb.AppendLine($"namespace {name}");
        cb.AppendLine("{");
        cb.IndentLevel++;

        var num = EmitContainingTypes(symbol, cb);
        return num + 1;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit parents when there is at least one syntax captured for the type. This
    /// method provides a richer way of doing things. Note that we still need the symbol because
    /// it is used at the end to emit the containing elements.
    /// </summary>
    static int EmitParentsFromSyntaxNodes(
        INamedTypeSymbol symbol,
        IEnumerable<BaseTypeDeclarationSyntax> syntaxes, ref TreeContext context, CodeBuilder cb)
    {
        List<string> pragmas = [];
        List<string> usings = [];

        // File-level pragmas and usings...
        foreach (var syntax in syntaxes)
        {
            var nschain = syntax.GetChain().Where(static x => x is BaseNamespaceDeclarationSyntax);
            PopulateFileLevelPragmas(pragmas, nschain);
            PopulateFileLevelUsings(usings, nschain);
        }
        if (pragmas.Count > 0) { foreach (var str in pragmas) cb.AppendLine(str); cb.AppendLine(); }
        if (usings.Count > 0) { foreach (var str in usings) cb.AppendLine(str); cb.AppendLine(); }

        // Namespaces, for simplicity we pick the first one...
        // LOW: process all namespaces in TypeNode.EmitParentsFromSyntaxNodes
        var num = 0;
        var item = syntaxes.First();
        var ichain = item.GetChain().Where(static x => x is BaseNamespaceDeclarationSyntax);
        foreach (var ns in ichain)
        {
            var name = ((BaseNamespaceDeclarationSyntax)ns).Name.ToString();
            cb.AppendLine($"namespace {name}");
            cb.AppendLine("{");
            cb.IndentLevel++;

            EmitNamespaceUsings((BaseNamespaceDeclarationSyntax)ns, cb);
            num++;
        }

        // Emitting parent types...
        num += EmitContainingTypes(symbol, cb);
        return num;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the containing types of the given one. Returns the number of opened levels
    /// that must be closed afterwards.
    /// </summary>
    static int EmitContainingTypes(INamedTypeSymbol symbol, CodeBuilder cb)
    {
        var tpchain = symbol.GetChain().Where(static x => x is INamedTypeSymbol);
        var num = 0;

        foreach (var tp in tpchain)
        {
            var type = (INamedTypeSymbol)tp;
            var head = GetTypeHeader(type);

            cb.AppendLine(head);
            cb.AppendLine("{");
            cb.IndentLevel++;
            num++;
        }
        return num;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to populate the list of file-level pragmas using the given syntax chain.
    /// </summary>
    static void PopulateFileLevelPragmas(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            if (ns.SyntaxTree.TryGetText(out var text))
            {
                foreach (var line in text.Lines)
                {
                    var str = line.ToString().Trim();
                    if (str.StartsWith("#pragma")) { if (!items.Contains(str)) items.Add(str); }
                    else if (str.Length != 0) break;
                }
            }
        }
    }

    /// <summary>
    /// Invoked to populate the given list of file-level usings using the given syntax chain.
    /// </summary>
    static void PopulateFileLevelUsings(List<string> items, IEnumerable<SyntaxNode> nschain)
    {
        foreach (var ns in nschain)
        {
            var comp = GetCompilation(ns);
            if (comp is null) continue;

            foreach (var item in comp.Usings)
            {
                var str = item.ToString().Trim();
                if (!string.IsNullOrWhiteSpace(str)) { if (!items.Contains(str)) items.Add(str); }
            }
        }

        // Gets the compilation unit syntax the given syntax node belongs to...
        static CompilationUnitSyntax? GetCompilation(SyntaxNode node)
        {
            while (node is not null)
            {
                if (node is CompilationUnitSyntax comp) return comp;
                node = node.Parent!;
            }
            return null;
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the namespace-level usings on the given code builder.
    /// </summary>
    static void EmitNamespaceUsings(BaseNamespaceDeclarationSyntax syntax, CodeBuilder cb)
    {
        List<string> items = []; foreach (var item in syntax.Usings)
        {
            var str = item.ToString().Trim();
            if (!string.IsNullOrWhiteSpace(str) && !items.Contains(str)) items.Add(str);
        }

        if (items.Count > 0)
        {
            foreach (var str in items) cb.AppendLine(str);
            cb.AppendLine();
        }
    }
}