namespace Yotei.Tools.Generators.Internal;

// ========================================================
/// <summary>
/// Represents a file in the source code generation hierarchy.
/// </summary>
/// <param name="fileName"></param>
internal sealed class FileNode(string fileName) : INode
{
    /// <inheritdoc/>
    INode INode.ParentNode => null!;

    /// <inheritdoc/>
    public override string ToString() => $"File: {FileName}";

    /// <summary>
    /// The name of the file this instance represents, without extensions.
    /// </summary>
    public string FileName { get; } = fileName.ThrowWhenNull();

    /// <summary>
    /// The list of child namespaces.
    /// <br/> Default equality: long namespace name, with its dot separated parts.
    /// </summary>
    public List<NamespaceNode> ChildNamespaces { get; } = [];

    // ----------------------------------------------------

    /// <inheritdoc/>
    public bool Validate(SourceProductionContext context)
    {
        foreach (var node in ChildNamespaces) if (!node.Validate(context)) return false;
        return true;
    }

    // ----------------------------------------------------

    /// <inheritdoc/>
    public void Emit(SourceProductionContext context, CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();

        PrintPragmas(cb);
        PrintUsings(cb);

        foreach (var node in ChildNamespaces) node.Emit(context, cb);
    }

    /// <summary>
    /// Emits the file-level pragmas.
    /// </summary>
    void PrintPragmas(CodeBuilder cb)
    {
        var items = new List<string>();
        foreach (var node in ChildNamespaces)
        {
            var tree = node.Syntax.SyntaxTree;
            if (tree.TryGetText(out var text))
            {
                foreach (var line in text.Lines)
                {
                    var str = line.ToString().Trim();
                    if (str.StartsWith("#pragma") && !items.Contains(str)) items.Add(str);
                    if (str.StartsWith("namespace")) break;
                }
            }
        }
        if (items.Count > 0)
        {
            foreach (var item in items) cb.AppendLine(item);
            cb.AppendLine();
        }
    }

    /// <summary>
    /// Emits the file-level usings.
    /// </summary>
    void PrintUsings(CodeBuilder cb)
    {
        var items = new List<string>();
        foreach (var node in ChildNamespaces)
        {
            var comp = node.Syntax.GetCompilationUnitSyntax();
            foreach (var item in comp.Usings)
            {
                var str = item.ToString();
                if (!string.IsNullOrWhiteSpace(str) && !items.Contains(str)) items.Add(str);
            }
        }
        if (items.Count > 0)
        {
            foreach (var item in items) cb.AppendLine(item);
            cb.AppendLine();
        }
    }
}