#if DEBUG && DEBUG_MEMBERWITH_GENERATOR
#define ENABLE_DEBUG
#endif

namespace Yotei.Generators.MemberWith;

// ========================================================
/// <summary>
/// <inheritdoc/>
/// </summary>
[Generator(LanguageNames.CSharp)]
internal class XGenerator : Tree.Generator, IIncrementalGenerator
{
    public static string NAME => "MemberWith";
    public static string NAMESPACE => "Yotei.Generators." + NAME;

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override bool LaunchDebugger =>
#if ENABLE_DEBUG
        true;
#else
        false;
#endif

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override void PostInitialization(IncrementalGeneratorPostInitializationContext context)
    {
        var cb = new CodeBuilder();
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine();

        cb.AppendLine(MemberWithSource.Code(NAMESPACE)); cb.AppendLine();

        context.AddSource($"{NAME}Attributes", cb.ToString());
    }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override string AttributeName
        => $"{NAMESPACE}.{MemberWithSource.AttributeLongName}";

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override Tree.CaptureLevel CaptureLevel => Tree.CaptureLevel.PropertyOrField;

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns><inheritdoc/></returns>
    public override Tree.IPropertyNode CreateProperty(
        Tree.ITypeNode parent,
        PropertyDeclarationSyntax syntax, IPropertySymbol symbol, SemanticModel model)
        => new XProperty(parent, syntax, symbol, model);

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns><inheritdoc/></returns>
    public override Tree.IFieldNode CreateField(
        Tree.ITypeNode parent,
        FieldDeclarationSyntax syntax, IFieldSymbol symbol, SemanticModel model)
        => new XField(parent, syntax, symbol, model);

    /// <summary>
    /// <inheritdoc></inheritdoc>/>
    /// </summary>
    /// <returns><inheritdoc/></returns>
    public override string GetFileName(
        Tree.ICaptured captured) => GetTopNamespaceFileName(captured);
}