namespace Yotei.Tools.Generators.Shared;

// ========================================================
/// <summary>
/// Represents a node in a source code generation hierarchy.
/// </summary>
internal interface INode
{
    /// <summary>
    /// The generator this instance is associated with.
    /// </summary>
    BaseGenerator Generator { get; }

    /// <summary>
    /// The parent node this instance belongs to, or null if it is a top-most one.
    /// </summary>
    INode? ParentNode { get; }

    /// <summary>
    /// Determines if this node is valid for source code generation purposes, or not.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    bool Validate(SourceProductionContext context);

    /// <summary>
    /// Invoked to emit the actual source code generated by this node.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="builder"></param>
    void Print(SourceProductionContext context, CodeBuilder builder);
}