namespace Yotei.Tools.Generators.Shared;

// ========================================================
/// <summary>
/// Represents a node in the source code generation hierarchy.
/// </summary>
/// <param name="parent"></param>
internal interface INode
{
    /// <summary>
    /// The generator this instance is associated with.
    /// </summary>
    BaseGenerator Generator { get; }

    /// <summary>
    /// The node this instance belong to, or null if this is a top-most one.
    /// </summary>
    INode? ParentNode { get; }

    /// <summary>
    /// Determines if this node is valid for source code generation purposes, or not.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    bool Validate(SourceProductionContext context);

    /// <summary>
    /// Invoked to emit the actual source code generated by this node.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="builder"></param>
    void Print(SourceProductionContext context, CodeBuilder builder);
}