#if DEBUG && DEBUG_CLONEABLE_GENERATOR
#define ENABLE_DEBUG
#endif

namespace Yotei.Generators.Cloneable;

// ========================================================
/// <inheritdoc cref="TreeGenerator">
/// </inheritdoc>
[Generator(LanguageNames.CSharp)]
public class Generator : Tree.Generator, IIncrementalGenerator
{
    const string NAMESPACE = "Yotei.Generators.Cloneable";

    /// <inheritdoc>
    /// </inheritdoc>
    public override bool LaunchDebugger =>
#if ENABLE_DEBUG
        true;
#else
        false;
#endif

    /// <inheritdoc>
    /// </inheritdoc>
    public override void PostInitialization(IncrementalGeneratorPostInitializationContext context)
    {
        var cb = new CodeBuilder();
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine();

        cb.AppendLine(CloneableTypeSource.Code(NAMESPACE)); cb.AppendLine();
        cb.AppendLine(CloneableMemberSource.Code(NAMESPACE));

        context.AddSource("Attributes", cb.ToString());
    }

    /// <inheritdoc>
    /// </inheritdoc>
    public override string AttributeName => NAMESPACE + "." + CloneableTypeSource.Name;

    /// <inheritdoc>
    /// </inheritdoc>
    public override Tree.TreeLevel TreeLevel => Tree.TreeLevel.Type;

    /// <inheritdoc>
    /// </inheritdoc>
    public override Tree.ICapturedType CreateCapturedType(
        SemanticModel semanticModel, Tree.IGenerator generator,
        TypeDeclarationSyntax typeSyntax, INamedTypeSymbol typeSymbol)
        => new ElementType(semanticModel, generator, typeSyntax, typeSymbol);

    /// <inheritdoc>
    /// </inheritdoc>
    public override string FileName(
        ImmutableArray<BaseNamespaceDeclarationSyntax> nsSyntaxChain,
        ImmutableArray<TypeDeclarationSyntax> tpSyntaxChain)
        => TopNamespaceFileName(nsSyntaxChain);
}