#if DEBUG && DEBUG_CLONEABLE_GENERATOR
#define ENABLE_DEBUG
#endif

namespace Yotei.Generators.Cloneable;

// ========================================================
/// <summary>
/// <inheritdoc/>
/// </summary>
[Generator(LanguageNames.CSharp)]
internal class XGenerator : Tree.Generator, IIncrementalGenerator
{
    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override bool LaunchDebugger =>
#if ENABLE_DEBUG
        true;
#else
        false;
#endif

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override void PostInitialization(IncrementalGeneratorPostInitializationContext context)
    {
        var cb = new CodeBuilder();
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine();

        cb.AppendLine(CloneableTypeSource.Code(NAMESPACE)); cb.AppendLine();
        cb.AppendLine(CloneableMemberSource.Code(NAMESPACE)); cb.AppendLine();

        context.AddSource($"{GENERATORNAME}.Attributes", cb.ToString());
    }
    public static string GENERATORNAME => "Cloneable";
    public static string NAMESPACE => $"Yotei.Generators.{GENERATORNAME}";

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override string AttributeName
        => $"{NAMESPACE}.{CloneableTypeSource.AttributeLongName}";

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public override Tree.CaptureLevel CaptureLevel => Tree.CaptureLevel.Type;

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns><inheritdoc/></returns>
    public override Tree.ITypeNode CreateType(
        Tree.INode parent,
        TypeDeclarationSyntax syntax, INamedTypeSymbol symbol, SemanticModel model)
        => new XType(parent, syntax, symbol, model);

    /// <summary>
    /// <inheritdoc></inheritdoc>/>
    /// </summary>
    /// <returns><inheritdoc/></returns>
    public override string GetFileName(
        Tree.ICaptured captured) => GetTopNamespaceFileName(captured);
}