using THost = Yotei.ORM.ISchemaEntry;
using TItem = Yotei.ORM.MetadataPair;

namespace Yotei.ORM;

// ========================================================
/// <summary>
/// An immutable object that represents the collection of metadata pairs associated with a given
/// entry in a record.
/// <br/> Metadata pairs with the same tag are not allowed.
/// </summary>
[Cloneable]
public partial interface ISchemaEntry : IEnumerable<TItem>, IEquatable<THost>
{
    /// <summary>
    /// The engine this instance is associated with.
    /// </summary>
    IEngine Engine { get; }

    /// <summary>
    /// The identifier by which this instance is known.
    /// </summary>
    [WithGenerator] IIdentifier Identifier { get; }

    /// <summary>
    /// Determines if the entry associated with this instance is a primary key, or part of a
    /// primary key group, or not. The framework supports at most one primary key group per
    /// schema.
    /// </summary>
    [WithGenerator] bool IsPrimaryKey { get; }

    /// <summary>
    /// Determines if the entry associated with this instance is a unique valued one, or part
    /// of a unique valued group, or not. The framework supports at most one unique valued group
    /// per schema.
    /// </summary>
    [WithGenerator] bool IsUniqueValued { get; }

    /// <summary>
    /// Determines if the entry associated with this instance is a read only one, or not. Read
    /// only entries in a record are assumed to be auto generated by the underlying database.
    /// </summary>
    [WithGenerator] bool IsReadOnly { get; }

    // ----------------------------------------------------

    /// <summary>
    /// Minimizes the memory consumption of this instance.
    /// </summary>
    void Trim();

    /// <summary>
    /// Gets the number of elements in this instance.
    /// </summary>
    int Count { get; }

    /// <summary>
    /// Gets the value of the metadata pair whose tag is given, or throw an exception if there
    /// is no metadata pair with that tag name in this instance.
    /// </summary>
    /// <param name="tag"></param>
    /// <returns></returns>
    object? this[string tag] { get; }

    /// <summary>
    /// Determines if this instance contains a metadata pair with the given tag.
    /// </summary>
    /// <param name="tag"></param>
    /// <returns></returns>
    bool Contains(string tag);

    /// <summary>
    /// Determines if this instance contains a metadata pair with the given tag and value, using
    /// a default comparer for the later.
    /// </summary>
    /// <param name="tag"></param>
    /// <param name="value"></param>
    /// <returns></returns>
    bool Contains(string tag, object? value);

    /// <summary>
    /// Determines if this instance contains a metadata pair with the given tag and value, using
    /// the given comparer for the later.
    /// </summary>
    /// <param name="tag"></param>
    /// <param name="value"></param>
    /// <param name="comparer"></param>
    /// <returns></returns>
    bool Contains(string tag, object? value, IEqualityComparer comparer);

    /// <summary>
    /// Tries to obtain the value of the metadata pair whose tag is given, if any.
    /// </summary>
    /// <param name="tag"></param>
    /// <param name="value"></param>
    /// <returns></returns>
    bool TryGetValue(string tag, out object? value);

    /// <summary>
    /// Returns an array with the elements in this instance.
    /// </summary>
    /// <returns></returns>
    TItem[] ToArray();

    /// <summary>
    /// Returns a list with the elements in this instance.
    /// </summary>
    /// <returns></returns>
    List<TItem> ToList();

    // ----------------------------------------------------

    /// <summary>
    /// Returns a new instance where the value of the metadata pair whose tag is given has been
    /// replaced by the new given one. If that pair did not exist, then a new one is added to
    /// this collection. If no changes are detected, returns the original instance instead.
    /// </summary>
    /// <param name="tag"></param>
    /// <param name="value"></param>
    /// <returns></returns>
    THost Replace(string tag, object? value);

    /// <summary>
    /// Returns a new instance where the given metadata pair has been added to it. If it had a
    /// metadata pair whose tag is the tag of the given pair, then an exception is thrown. If no
    /// changes are detected, returns the original instance instead.
    /// </summary>
    /// <param name="item"></param>
    /// <returns></returns>
    THost Add(TItem item);

    /// <summary>
    /// Returns a new instance where the metadata pairs of the given range have been added to it.
    /// If it had a metadata pair whose tag is any of the given ones, then an exception is thrown.
    /// If no changes are detected, returns the original instance instead.
    /// </summary>
    /// <param name="range"></param>
    /// <returns></returns>
    THost AddRange(IEnumerable<TItem> range);

    /// <summary>
    /// Returns a new instance where the metadata pair whose tag is given has been removed, if
    /// any. If no changes are detected, returns the original instance instead.
    /// </summary>
    /// <param name="tag"></param>
    /// <returns></returns>
    THost Remove(string tag);

    /// <summary>
    /// Returns a new instance where all the original metadata pairs have been removed. If no
    /// changes are detected, returns the original instance instead.
    /// </summary>
    /// <returns></returns>
    THost Clear();
}