using THost = Yotei.ORM.Records.ISchemaEntry;
using TItem = Yotei.ORM.Records.MetadataPair;

namespace Yotei.ORM.Records;

// ========================================================
/// <summary>
/// An immutable object that contains the metadata that describes a given entry in a record.
/// </summary>
[Cloneable]
public partial interface ISchemaEntry : IEnumerable<TItem>
{
    /// <summary>
    /// The engine this instance is associated with.
    /// </summary>
    IEngine Engine { get; }

    /// <summary>
    /// The identifier by which this instance is known.
    /// </summary>
    [WithGenerator] IIdentifier Identifier { get; }

    /// <summary>
    /// Determines if the entry associated with this instance is a primary key, or part of a
    /// primary key group, or not. The framework supports at most one primary key group per
    /// schema.
    /// </summary>
    [WithGenerator] bool IsPrimaryKey { get; }

    /// <summary>
    /// Determines if the entry associated with this instance is a unique valued one, or part
    /// of a unique valued group, or not. The framework supports at most one unique valued group
    /// per schema.
    /// </summary>
    [WithGenerator] bool IsUniqueValued { get; }

    /// <summary>
    /// Determines if the entry associated with this instance is a read only one, or not. Read
    /// only entries in a record are assumed to be auto generated by the underlying database.
    /// </summary>
    [WithGenerator] bool IsReadOnly { get; }

    // ----------------------------------------------------

    /// <summary>
    /// Gets the number of metadata pairs in this instance.
    /// </summary>
    int Count { get; }

    /// <summary>
    /// Gets the value of the metadata pair whose tag name is given. If no metadata pair is
    /// found with that tag name then an exception is thrown.
    /// </summary>
    /// <param name="tag"></param>
    /// <returns></returns>
    object? this[string tag] { get; }

    /// <summary>
    /// Determines if this instance contains a metadata pair with the given tag name, or not.
    /// </summary>
    /// <param name="tag"></param>
    /// <returns></returns>
    bool Contains(string tag);

    /// <summary>
    /// Tries to obtain the value of the metadata pair with the given tag name.
    /// </summary>
    /// <param name="tag"></param>
    /// <param name="value"></param>
    /// <returns></returns>
    bool TryGetValue(string tag, out object? value);

    // ----------------------------------------------------

    /// <summary>
    /// Obtains an instance where the value of the metadata pair whose tag name is given has
    /// been replaced by the new given one. If such pair was not found, a new one is added to
    /// the returned instance.
    /// </summary>
    /// <param name="tag"></param>
    /// <param name="value"></param>
    /// <returns></returns>
    THost Replace(string tag, object? value);

    /// <summary>
    /// Obtains an instance where the given metadata pair has been added to the original one.
    /// If its tag name was already used in the original instance, then an exception is thrown.
    /// </summary>
    /// <param name="item"></param>
    /// <returns></returns>
    THost Add(TItem item);

    /// <summary>
    /// Obtains an instance where the metadata pairs from the given range have been added to
    /// the original one. If the tag name of any of those pairs was already used in the original
    /// instance, then an exception is thrown.
    /// </summary>
    /// <param name="range"></param>
    /// <returns></returns>
    THost AddRange(IEnumerable<TItem> range);

    /// <summary>
    /// Obtains an instance where the metadata pair with the given tag name has been removed
    /// from the original collection.
    /// </summary>
    /// <param name="tag"></param>
    /// <returns></returns>
    THost Remove(string tag);

    /// <summary>
    /// Obtains an instance where the first metadata pair that matches the given predicate has
    /// been removed from the original collection.
    /// </summary>
    /// <param name="predicate"></param>
    /// <returns></returns>
    THost Remove(Predicate<TItem> predicate);

    /// <summary>
    /// Obtains an instance where the last metadata pair that matches the given predicate has
    /// been removed from the original collection.
    /// </summary>
    /// <param name="predicate"></param>
    /// <returns></returns>
    THost RemoveLast(Predicate<TItem> predicate);

    /// <summary>
    /// Obtains an instance where all the metadata pairs that match the given predicate have
    /// been removed from the original collection.
    /// </summary>
    /// <param name="predicate"></param>
    /// <returns></returns>
    THost RemoveAll(Predicate<TItem> predicate);

    /// <summary>
    /// Obtains an instance where all the original elements have been removed.
    /// </summary>
    /// <returns></returns>
    THost Clear();
}