namespace Yotei.Generators.Tree;

// ========================================================
/// <summary>
/// Represents a source code file in the hierarchy.
/// </summary>
internal class FileNode
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="name">The name of the file to be emitted.</param>
    public FileNode(string name) => Name = name.NotNullNotEmpty(nameof(name));

    /// <inheritdoc>
    /// </inheritdoc>
    public override string ToString() => $"File: {Name}";

    /// <summary>
    /// The name of the file to be emitted, which must be unique for a given generator.
    /// </summary>
    public string Name { get; }

    // ----------------------------------------------------

    /// <summary>
    /// The collection of child namespace nodes.
    /// </summary>
    List<NamespaceNode> ChildNamespaces { get; } = new();

    NamespaceNode LocateChildNamespace(ICaptured captured)
    {
        var item = captured.AsCapturedType();
        var nsSyntax = item.NamespaceSyntaxChain[0];
        var nsName = nsSyntax.Name.LongName();

        var node = ChildNamespaces.Find(x => x.Name == nsName);
        if (node == null)
        {
            node = new NamespaceNode(item, 0);
            ChildNamespaces.Add(node);
        }
        return node;
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to register into this instance the given captured element.
    /// </summary>
    /// <param name="captured"></param>
    public void Register(ICaptured captured)
    {
        var node = LocateChildNamespace(captured);
        node.Register(captured, 1, 0);
    }

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to validate this instance and its contents, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public bool Validate(SourceProductionContext context)
    {
        foreach (var node in ChildNamespaces) if (!node.Validate(context)) return false;
        return true;
    }

    /// <summary>
    /// Invoked to generate the source code for this instance and its contents, if any.
    /// </summary>
    /// <param name="context"></param>
    /// <param name="cb"></param>
    public void Print(SourceProductionContext context, CodeBuilder cb)
    {
        cb.AppendLine("// <auto-generated/>");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();

        foreach (var node in ChildNamespaces) node.Print(context, cb);

        var name = Name + ".g.cs";
        var code = cb.ToString();
        context.AddSource(name, code);
    }
}