namespace Yotei.Tools.CloneGenerator;

// ========================================================
/// <summary>
/// <inheritdoc/>
/// </summary>
[Generator(LanguageNames.CSharp)]
internal class CloneGenerator : CoreGenerator.CoreGenerator
{
#if DEBUG_CLONE_GENERATOR2
    /// <inheritdoc/>
    protected override bool LaunchDebugger => true;
#endif

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    protected override Type[] TypeAttributes { get; } = [
        typeof(CloneableAttribute),
        typeof(CloneableAttribute<>),];

    // ----------------------------------------------------

    /// <summary>
    /// Gets the version of the assembly of this source code generator.
    /// </summary>
    public static string VersionDoc => Assembly.GetExecutingAssembly().GetName().Version.ToString();

    /// <summary>
    /// A string with the 'GeneratedCodeAttribute' attribute appropriate for documenting the source
    /// code generated by this generator.
    /// </summary>
    public static string AttributeDoc => $$"""
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(CloneGenerator)}}", "{{VersionDoc}}")]
        """;
}