namespace Yotei.Tools.CloneGenerator;

// ========================================================
/// <summary>
/// <inheritdoc/>
/// </summary>
[Generator(LanguageNames.CSharp)]
internal class CloneGenerator : TreeGenerator
{
#if DEBUG_CLONE_GENERATOR__
    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    protected override bool LaunchDebugger => true;
#endif

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    protected override List<Type> TypeAttributes { get; } = [
        typeof(NamedAttribute), // DEBUG-ONLY remove type when done...
        typeof(CloneableAttribute),
        typeof(CloneableAttribute<>),];

    // DEBUG-ONLY remove attribute types when done...
    protected override List<Type> PropertyAttributes { get; } = [
        typeof(NamedAttribute),];

    // DEBUG-ONLY remove attribute types when done...
    protected override List<Type> MethodAttributes { get; } = [
        typeof(NamedAttribute),];

    // ----------------------------------------------------

    /// <summary>
    /// Gets the version of the assembly of this source code generator.
    /// </summary>
    public static string VersionDoc => Assembly.GetExecutingAssembly().GetName().Version.ToString();

    /// <summary>
    /// A string with the 'GeneratedCodeAttribute' attribute appropriate for documenting the source
    /// code generated by this generator.
    /// </summary>
    public static string AttributeDoc => $$"""
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(CloneGenerator)}}", "{{VersionDoc}}")]
        """;
}