namespace Yotei.Tools.CloneGenerator;

// ========================================================
/// <summary>
/// <inheritdoc/>
/// </summary>
[Generator(LanguageNames.CSharp)]
internal class CloneGenerator : TreeGenerator
{
#if DEBUG_CLONE_GENERATOR__
    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    protected override bool LaunchDebugger => true;
#endif

    // DEBUG-ONLY: remove when done...
    protected override void OnInitialize(IncrementalGeneratorPostInitializationContext context)
    {
        var type = typeof(Foo<,>);
        var item = type.GetMethod("MyMethod");

        var options = EasyNameMethodInfo.Default with
        { ParameterOptions = EasyNameParameterInfo.Default };
        var name = item.EasyName(options);
        Debug.Assert(name != null);
    }

    // DEBUG-ONLY: remove when done...
    public partial class Foo<K, T>
    {
        [Named]
        public void MyMethod([IsNullable] K? one) { }
    }

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    protected override List<Type> TypeAttributes { get; } = [
        typeof(NamedAttribute), // DEBUG-ONLY: remove when done...
        typeof(CloneableAttribute),
        typeof(CloneableAttribute<>),];

    // DEBUG-ONLY: remove when done...
    protected override List<Type> PropertyAttributes { get; } = [
        typeof(NamedAttribute),];

    // DEBUG-ONLY: remove when done...
    protected override List<Type> MethodAttributes { get; } = [
        typeof(NamedAttribute),];

    // DEBUG-ONLY: remove when done...
    protected override List<Type> FieldAttributes { get; } = [
        typeof(NamedAttribute),];

    // ----------------------------------------------------

    /// <summary>
    /// Gets the version of the assembly of this source code generator.
    /// </summary>
    public static string VersionDoc => Assembly.GetExecutingAssembly().GetName().Version.ToString();

    /// <summary>
    /// A string with the 'GeneratedCodeAttribute' attribute appropriate for documenting the source
    /// code generated by this generator.
    /// </summary>
    public static string AttributeDoc => $$"""
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(CloneGenerator)}}", "{{VersionDoc}}")]
        """;
}