namespace Yotei.Tools.Generators.Shared;

// ========================================================
/// <summary>
/// Represents a file into which source code can be emitted.
/// </summary>
internal class FileBuilder : CodeBuilder, INode
{
    /// <summary>
    /// Initializes a new instance.
    /// </summary>
    /// <param name="generator"></param>
    /// <param name="fileName"></param>
    public FileBuilder(BaseGenerator generator, string fileName)
    {
        Generator = generator.ThrowWhenNull();
        FileName = fileName.NotNullNotEmpty();

        NamespaceNodes = new NamespaceList(this);
    }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <returns></returns>
    public override string ToString() => $"File: {FileName}";

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    public BaseGenerator Generator { get; }

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    INode? INode.ParentNode => null;

    /// <summary>
    /// The file name of this instance, without extensions.
    /// </summary>
    public string FileName { get; }

    /// <summary>
    /// The collection of namespace nodes registered in this instance.
    /// </summary>
    public NamespaceList NamespaceNodes { get; }
    public class NamespaceList : CustomList<NamespaceNode>
    {
        readonly FileBuilder Master;
        public NamespaceList(FileBuilder master)
        {
            Master = master;
            OnValidate = (item, add) =>
            {
                item.ThrowWhenNull();
                if (add && !ReferenceEquals(Master, item.ParentNode)) throw new ArgumentException(
                    "Parent node of the given item is not this instance.");
                return item;
            };
            OnCompare = (item, other) => item.Name == other.Name;
            OnSameElement = ReferenceEquals;
            OnAcceptDuplicate = (item, other) => false;
        }
    }

    // ----------------------------------------------------

    /// <summary>
    /// Registers the given candidate.
    /// </summary>
    /// <param name="candidate"></param>
    public void Register(Candidate candidate)
    {
        candidate.ThrowWhenNull();

        var syntax = candidate.NamespaceSyntaxChain[0];
        var name = syntax.Name.ShortName();
        var index = NamespaceNodes.IndexOf(x => x.Name == name);
        var node = index >= 0
            ? NamespaceNodes[index]
            : Generator.CreateNode(this, syntax);

        node.Register(candidate, 1, 0);
    }

    // ----------------------------------------------------

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public bool Validate(SourceProductionContext context) => throw null;

    // ----------------------------------------------------

    /// <summary>
    /// Invoked to emit the actual source code generated by this node.
    /// </summary>
    /// <param name="context"></param>
    public virtual void Print(SourceProductionContext context) => throw null;

    /// <summary>
    /// <inheritdoc/>
    /// </summary>
    void INode.Print(SourceProductionContext context, CodeBuilder _) => Print(context);
}